### ISSUE TITLE
DB sync across files

### ISSUE THREAD

**Issue by Herobrine643928** [JaylyDev/ScriptAPI#251]
**Describe the bug**
Having one database across multiple files while being written and read causes the updated values to not be read properly.
**Expected behavior**
The most recently saved value should be displayed, regardless of the file it was logged in.
**Screenshots**
![image](https://github.com/JaylyDev/ScriptAPI/assets/94234093/74144784-1e63-440c-9bb0-d4693e4e85a2)

1. Send 'same' in chat to log value of 10 to DB.
2. Send 'other' in chat to log value of 50 to DB. Console logs the value from before DB being set.
3. Send anything  else to return the value of the DB (from the first file).
4. Doing these in order should return the value of 50 on step 3, but the value of 10 is still sent, unless the world is reloaded.
Code below:
```js
import { world } from "@minecraft/server";
import { JaylyDB } from './database/scoreboardDB.js';
import { testCmd } from "./command.js";
const test = new JaylyDB('testing');
world.events.beforeChat.subscribe(evd => {
	const player = evd.sender;
	if (evd.message == 'same') {
		test.set(player.id, 10);
	} if (evd.message == 'other') {
		testCmd(player);
	} else {
		console.warn('Same file: ' + test.get(player.id))
	};
})
//OTHER FILE BELOW
import { JaylyDB } from './database/scoreboardDB.js';
const test = new JaylyDB('testing');
export function testCmd(player) {
	console.warn('Other file: ' + test.get(player.id));
	test.set(player.id, 50);
}

**Comment by JaylyDev** [comment]
This issue should be fixed in jaylydb 1.1 (1.20.10+)
