### ISSUE TITLE
JaylyDB doesn't write properly

### ISSUE THREAD

**Issue by Herobrine643928** [JaylyDev/ScriptAPI#295]
**Describe the bug**
When I try to set a value in a defined database, it doesn't stick. It works when I call the database immediately after setting it, but only then.
I am running the latest version of the database; 1.1.2, but I was having issues with this on a previous version as well. (1.1.0)
1.20.12 Stable mc version, with the database being defined in a file and then imported into the other files (could that be the issue?)
**Expected behavior**
The database should set permanently.
**Screenshots**
![image](https://github.com/JaylyDev/ScriptAPI/assets/94234093/6340ea0c-dbb4-4125-9751-b6a936e56ec3)
```js
import { moneyDB } from '../utility/references/config.js'; //Where it is defined as const moneyDB = new JaylyDB('money');

console.warn('Before: ', moneyDB.get(player.id));
moneyDB.set(player.id, '1000.00');
console.warn('After: ', moneyDB.get(player.id));
system.runTimeout(() => console.warn('After 2: ', moneyDB.get(player.id)), 20);
```

**Comment by JaylyDev** [comment]
We tried and couldn't reproduce this issue unfortunately with your provided code snippet, perhaps there are other scripts that modified the db at the same time?

**Comment by Herobrine643928** [comment]
I have tested some stuff and have narrowed down the problem to a small chunk of code.

**Comment by Herobrine643928** [comment]
I have done some testing and have narrowed down the issue to a small chunk of code.
```js
const testDB = new JaylyDB('testing');
//In chat event or similar
	testDB.set(player.id, JSON.stringify([{ test: 10 }, { test: 20 }]));
	let testing = JSON.parse(testDB.get(player.id));
	//testing.forEach(v => v.test += 10);
	//testing.forEach(v => v.tester = true);
	//testing.forEach(v => v.tester = undefined);
	testDB.set(player.id, JSON.stringify(testing));
	for (const [k, v] of testDB.entries()) {
		console.warn(k, v)
	}
	system.runTimeout(() => {
		for (const [k, v] of testDB.entries()) {
			console.warn(k, v)
		}
	}, 20)
```
Steps to reproduce:
1. Run the above code once. This sets the initial values for the DB.
2. Comment out the first line, and uncomment the third line. Reload the script. This will now print increasing values in the console. As intended!
3. Re-comment the third line, and uncomment the fourth line, adding a new property to each element and setting it to 'true'. Run it in game, and note that all is well.
4. Re-comment line four, and uncomment the fifth and final comment. Run it in game. Note how the immediate DB test says that the property is deleted, but the delayed one says it isn't.
5. Re-comment lines except for the first one and the warnings. This doesn't work now either! Setting the properties back to their initial state works in the first DB console warn, but not the second one.

Either the excessive amount of reloads is causing issues, or I am going crazy. But here is my content log from my own testing.
![image](https://github.com/JaylyDev/ScriptAPI/assets/94234093/7e811549-cc72-4197-a5fd-24c904b0627d)
Second to last line is the immediate DB warn, and the last is the delayed DB warn- showing they are not synced.

**Comment by PAPISOP** [comment]
Hello, I want to say that the jayly database actually doesn't delete the old value of the key when a new value is set to that key by ```db.set(key, value);```. So, in the set code, the code doesn't delete the old key and its value, instead the code adds a new key and value to the database which makes the database doesn't write data properly. Here's a fixed code which will delete the old key and its value during set, and adds a new key (same key which was deleted but with new value) and value to the database, basically the database will update the key in database.

Replace the set code in your database code to the below code:
```js
set(key, value) {
        if (!allowedTypes.includes(typeof value))
            throw new TypeError("JaylyDB::set only accepts a value of string, number, or boolean.");
        if (this.localState.get(key)?.decoded_value === value)
            return this;
        const encoded = DisplayName.stringify({ [key]: value }, this.salt);
        if (encoded.length > 32767)
            throw new RangeError("JaylyDB::set only accepts a string value less than 32767 characters.");
        // push change to disk
        const participant = this.localState.get(key);
        if (participant) {
            this.objective.removeParticipant(participant.identity);
            this.localState.delete(key);
        }
        this.objective.setScore(encoded, 0);
        const data = {
            encoded_value: encoded,
            decoded_value: value,
            identity: this.objective.getParticipants().find(participant => participant.displayName === encoded),
        };
        this.localState.set(key, data);
        return this;
    }
    ```
    The above code is a js code and it adds "participant" constant which will check if the key already exists in the database or not, it will return undefined if the key doesn't exist, and if it does exists then it will remove the key from the database and the new value will be updated to the key.

**Comment by JaylyDev** [comment]
@PAPISOP nice catch! Thanks for providing the code, however I don't accept code fixes from issues but would recommend create a pull request that changes the TypeScript file (not the autogenerated javascript file).

**Comment by PAPISOP** [comment]
@JaylyDev I created a pull request, please review it.
