### ISSUE TITLE
Remove <1.19.30 modules typings when 1.19.40 stable releases

### ISSUE THREAD

**Issue by JaylyDev** [JaylyDev/ScriptAPI#31]
Remove pre 1.19.40 modules such as mojang-minecraft, mojang-gametest, mojang-minecraft-ui, mojang-minecraft-server-admin and mojang-net from package.json because they won't work in script api.

**Comment by bot174** [comment]
NO

**Comment by skybird23333** [comment]
just move it to a branch 😡
