### ISSUE TITLE
Document API Errors

### ISSUE THREAD

**Issue by JaylyDev** [JaylyDev/ScriptAPI#49]
**Is your feature request related to a problem? Please describe.**
Mainly just want to document frequently seen errors thrown by the API and not vanilla js:
- Native function does not exist.
- Native object bound to prototype does not exist.
- No constructor for native class '%s'.
- value is not iterable (in some native iteration object)
etc

**Additional context**
If you can document all API errors

**Comment by ConsoleTerm** [comment]
statusMessage will not be added anymore, for one simple reason, statusMessage returns a text that does not depend on the client's language, and it makes no sense to use this alternative to read data from commands, you will have to wait for future API implementations

**Comment by ConsoleTerm** [comment]
but value is not iteratorble is vanilla js error
